### ISSUE TITLE
Creating variant output file

### ISSUE THREAD

**Issue by bdeonovic** [raphael-group/multibreak-sv#7]
I'm having a bit of trouble understanding the MBSV output. I'm interested in generating a file that lists the variants position along with the alleles associated with the variant. Can I produce such a file from the MBSV output?

**Comment by annaritz** [comment]
This information is included in the GASV clusters file.  The output of MBSV assigns probabilities to the clusters (SVs) being supported by $k$ or more reads (the finalbreakpoints file) and also assigns probabilities to the alignments themselves (the finalassignment file).  You can identify high-probability SVs from the finalbreakpoints file and determine the variant information by looking the cluster ID up in the GASV clusters file. In our analyses, we used the alignment probabilities to identify a probability for each SV, which is a bit different than using the finalbreakpoints file.  Details are in the paper.

**Comment by bdeonovic** [comment]
So my finalbreakpoints file looks like:

``` bash

c150490 1000    286.0   714.0
c285797 1000    1.0 0.0 0.0 0.0 0.0 999.0
c185205 1000    297.0   703.0
c185206 1000    308.0   692.0
c185207 1000    1.0 0.0 999.0
c251300 1000    1.0 0.0 999.0
c259236 1000    258.0   742.0
c299474 1000    1.0 0.0 0.0 999.0
c248272 1000    1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 999.0
c278079 1000    1.0 0.0 0.0 0.0 0.0 0.0 0.0 999.0
...
```

and my finalassignment file looks like:

``` bash
longread_7484233    -1  0.285   error
longread_7484233    0   0.714   longread_7484233
longread_7484242    -1  0.0 error
longread_7484242    0   0.999   longread_7484242
longread_7484243    -1  0.0 error
longread_7484243    0   0.999   longread_7484243
longread_7484244    -1  0.0 error
longread_7484244    0   0.999   longread_7484244
longread_7484245    -1  0.0 error
longread_7484245    0   0.999   longread_7484245
...
```

and my gasv.in.clusters looks like:

``` bash
c1  1   282.8   I-  longread_3223104_0.5-1.5    1   1   14552, 187466, 14152, 187466, 14552, 187066, 14552, 187466
c2  2   143.1   I+  longread_1561209_0.2-1.2, longread_3545236_0.8-1.8  1   1   14399, 188515, 14399, 188460, 14744, 188115, 14799, 188115
c3  1   883.2   I-  longread_3264843_0.1-1.1    1   1   15618, 190997, 15018, 190997, 16618, 189397, 16618, 189997
c4  1   424.3   D   longread_7548861    1   1   15820, 17049, 16420, 17049, 15820, 16449, 15820, 17049
c5  22  -1  D   longread_7474303, longread_7420374, longread_7420373, longread_7420375, longread_7521832, longread_7474302, longread_7466906, longread_7470407, longread_7466905, longread_7512530, longread_7512531, longread_7512533, longread_7452659, longread_7452658, longread_7513187, longread_7513185, longread_7513184, longread_7404800, longread_7452660, longread_7452657, longread_7513183, longread_7513186  1   1   16865, 17708
c5.0    13  96.9    D   longread_7512530, longread_7512531, longread_7512533, longread_7452659, longread_7452658, longread_7513187, longread_7513185, longread_7513184, longread_7404800, longread_7452660, longread_7452657, longread_7513183, longread_75131861   1   17002, 19086, 16865, 19086, 16865, 18949
c5.1    6   82.7    D   longread_7474303, longread_7420374, longread_7420373, longread_7420375, longread_7521832, longread_7474302  1   1   16725, 17708, 16608, 17708, 16608, 17591
c5.2    6   41  D   longread_7420375, longread_7521832, longread_7474302, longread_7466906, longread_7470407, longread_7466905  1   1   16672, 18029, 16614, 18029, 16614, 17971
c5.3    4   10.6    D   longread_7466906, longread_7470407, longread_7466905, longread_7512530  1   1   16641, 18365, 16626, 18365, 16626, 18350
c5.4    5   2.8 D   longread_7466906, longread_7470407, longread_7466905, longread_7512531, longread_7512533    1   1   16618, 18365, 16614, 18365, 16614, 18361
...
```

I'm still a bit unclear how to combine these to get variant calls.

**Comment by annaritz** [comment]
Hi -

I've written a post-processing script for a quick way to get this information.  The script is located in src/, and will be copied to bin/ if you execute the install script.  I've updated the Manual with information about how to run it, and I've copied the relevant parts here.  Note that this doesn't get you exactly the scores from the original paper, which used the notion of the cluster diagram to compute SV probabilities rather than frequencies.  This should be a good starting point, though.

> Output File Parser: (New Sept 2015) ###########################################
> The Python function quick-post-process.py takes output of MultiBreak-SV and
> produces a file with two different scores for each cluster: an SVFrequency score
> (the proportion of times that the cluster was supported by any
> multi-breakpoint-reads in the mapping over all sampled mappings)
> and an AverageProbability score (the average of all the probabilities
> of all supporting multi-breakpoint-reads for each cluster).
> ...

Usage: quick-post-process.py [options]
Outputs a file with Cluster information, SVFrequency, and AverageProbability.

Options:
  -h, --help            show this help message and exit
  --clustersfile=CLUSTERSFILE
                        GASV clusters file. Required.
  --finalbreakpointfile=FINALBREAKPOINTFILE
                        Final Breakpoint File. Required.
  --finalassignmentfile=FINALASSIGNMENTSFILE
                        Final Assignments File. Required.
  --minsupport=MINSUPPORT
                        Minimum support (# of multi-breakpoint-mappings) for
                        SVs to count towards SVFrequency.  In other words, we
                        "count" an SV as identified in a mapping if it
                        contains at least this many multi-breakpoint-reads.
                        Default=2.
  --outfile=OUTFILE     Outfile name. Default=out.txt.

Example Run (After running III(c)):

```
python bin/quick-post-process.py \
       --clustersfile MultiBreak-SV-example/infiles/gasv.clusters \
       --finalbreakpointfile MultiBreak-SV-example/outfiles/multibreaksv-randinit.finalbreakpoints.longburnin \
       --finalassignmentfile MultiBreak-SV-example/outfiles/multibreaksv-randinit.finalassignment.longburnin \
       --outfile MultiBreak-SV-example/outfiles/processed-output.txt
```

Try running this script on your output and let me know if you have any questions.  Also let me know if you come across any issues, since this is very new code. Thanks - Anna

**Comment by bdeonovic** [comment]
Thanks @annaritz I appreciate your prompt responses! I will let you know how this turns out.

**Comment by annaritz** [comment]
Closing this issue; please open another one if you need to. Thanks -
